---
title: "CUNY SPS HW14"
author: "Chinedu Onyeka"
date: "2023-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<center><h3><b>Questions</b></h3></center>
This week, we’ll work out some Taylor Series expansions of popular functions.
<li>	$f(x) = 1/(1-x)$ </li>
<li>	$f(x) = e^x$ </li>
<li>	$f(x) = ln(1 + x)$ </li>
<li>	$f(x)=x^\frac{1}{2}$ </li>
For each function, only consider its valid ranges as indicated in the notes when you are computing the Taylor Series expansion. Please submit your assignment as an R- Markdown document.

</br>

<center><h3><b>Solution</b></h3></center>

Taylor Series is defined as 
$$
\begin{split}
f(x) &= \sum\limits_{n=0}^{\infty}\frac{f^{(n)}(a)}{n!}(x-a)^n \\
 &= f(a) + f'(a)(x-a) + \frac{f''(a)}{2!}(x-a)^2 + \frac{f'''(a)}{3!}(x-a)^3 + \frac{f'^v(a)}{4!}(x-a)^4 + \  ... 
\end{split}
$$

While the Maclaurin Series is defined as:  
$$
\begin{split}
f(x) &= \sum\limits_{n=0}^{\infty}\frac{f^{(n)}(0)}{n!}x^n \\
 &= f(0) + f'(0)x + \frac{f''(0)}{2!}x^2 + \frac{f'''(0)}{3!}x^3 + \frac{f'^v(0)}{4!}x^4 + \  ... 
\end{split}
$$
<br>

<center><h3><b>Solution 1</b></h3></center>
$f(x) = \frac{1}{1-x}$

Find the first n-derivatives of f(x).

$f^0(c) = \frac{1}{(1-a)}$,

$f'(x)= \frac{1}{(1-x)^2};\ => f'(c) \frac{1}{(1-a)^2}$

$f''(x) = \frac{2}{(1-x)^3}\ => f''(c) = \frac{2}{(1-a)^3}$

$f'''(x) = \frac{6}{(1-x)^4}\ => f'''(c) = \frac{6}{(1-a)^4}$

$f'^v(x) = \frac{24}{(1-x)^5}\ => f'^v(c) = \frac{24}{(1-a)^5}$

Following the definition of the Taylor's series given above, 

$$
\begin{split}
f(x) &= \frac{1}{(1-a)0!}(x-a)^0 + \frac{1}{(1-a)^2 1!}(x-a)^1 + \frac{2}{(1-a)^3 2!}(x-a)^2 + \frac{6}{(1-a)^4 3!}(x-a)^3 + \frac{24}{(1-a)^5 4!}(x-a)^4 + ... \\
&= \frac{1}{(1-a)} + \frac{1}{(1-a)^2}(x-a) + \frac{2!}{(1-a)^3 2!}(x-a)^2 + \frac{3!}{(1-a)^4 3!}(x-a)^3 + \frac{4!}{(1-a)^5 4!}(x-a)^4 + ... \\
&= \frac{1}{(1-a)} + \frac{1}{(1-a)^2}(x-a) + \frac{1}{(1-a)^3}(x-a)^2 + \frac{1}{(1-a)^4}(x-a)^3 + \frac{1}{(1-a)^5}(x-a)^4 + ... \\
&= \sum\limits_{n=0}^{\infty} \frac{1}{(1-a)^{n+1}}(x-a)^n
\end{split}
$$

The Maclaurin Series of $f(x),\ a=0$, $f(x) = \sum\limits_{n=0}^{\infty} x^n = 1 + x + x^2 + x^3 + x^4 + ...$.

The series converges if $|x|<1$, Hence, the valid range is $(-1, 1)$.
<br>

<center><h3><b>Solution 2</b></h3></center>
$f(x) = e^x$


Find first n-derivatives.
Note: $f(x) = f'(x) = f''(x) = f'''(x) = f'^v(x) = f^n(x) = e^x$  
Therefore,  
$f^0(a) = f'(a) = f''(a) = f'''(a) = f'^v(a) = f^n(a) = e^a$  

Following the definition of the Taylor Series, 

$$
\begin{split}
f(x) &= \frac{e^a}{0!}(x-a)^0 + \frac{e^a}{1!}(x-a)^1 + \frac{e^a}{2!}(x-a)^2 + \frac{e^a}{3!}(x-a)^3 + ...\\
&= e^a + e^a(x-a) + e^a\frac{(x-a)^2}{2!} + e^a\frac{(x-a)^3}{3!} + ...\\
&= e^a \sum\limits_{n=0}^{\infty} \frac{(x-a)^n}{n!}
\end{split}
$$

The Maclaurin Series of $f(x),\ a=0$, is given by  
$f(x) = \sum\limits_{n=0}^{\infty} \frac{x^n}{n!} = 1 + x + \frac{x^2}{2} + \frac{x^3}{6} + \frac{x^4}{24} + ...$.

**Using the Ratio Test**: 

$\frac{a_{n+1}}{a_n} = \frac{x^{n+1}}{(n+1)!}\times\frac{n!}{x^n} = \frac{x \times x^n \times n!}{(n+1)\times n! \times x^n} = \frac{x}{n+1}$

$L = \lim\limits_{n\to\infty}\frac{x}{n+1} = 0$ and $L<1$.

This series will converge for any $x$, so the valid range is $(-\infty, \infty)$.
<br>

<center><h3><b>Solution 3</b></h3></center>
$f(x) = ln(1+x)$


Find first four derivatives.

$f^0(x) = ln(1+x),\ => f^0(a) = ln(1+a)$

$f'(x) = \frac{1}{x+1},\ => f'(c) = \frac{1}{a+1}$

$f''(x) = -\frac{1}{(x+1)^2},\ => f''(a) = -\frac{1}{(a+1)^2}$

$f'''(x) = \frac{2}{(x+1)^3},\ => f'''(a) = \frac{2}{(a+1)^3}$

$f'^v(x) = -\frac{6}{(x+1)^4},\ => f'^v(a) = -\frac{6}{(a+1)^4}$

Following the definition of the Taylor Series, 

$$
\begin{split}
f(x) &= \frac{ln(1+a)}{0!}(x-a)^0 + \frac{1}{(a+1)1!}(x-a)^1 - \frac{1}{(a+1)^2 2!}(x-a)^2 + \frac{2}{(a+1)^3 3!}(a-c)^3 - \frac{6}{(a+1)^4 4!}(x-a)^4 + ...\\
&= ln(1+a) + \frac{1}{(a+1)}(x-a) - \frac{1!}{(a+1)^2 2\times1!}(x-a)^2 + \frac{2!}{(a+1)^3 3\times2!}(x-a)^3 - \frac{3!}{(a+1)^4 4\times3!}(x-a)^4 + ...\\
&= ln(1+a) + \frac{1}{(a+1)}(x-a) - \frac{1}{2(a+1)^2}(x-a)^2 + \frac{1}{3(a+1)^3}(x-a)^3 - \frac{1}{4(a+1)^4}(x-a)^4 + ...\\
&= ln(1+a) + \sum\limits_{n=1}^{\infty} (-1)^{n+1}\frac{(x-a)^n}{n(a+1)^n}
\end{split}
$$

The Maclaurin Series of $f(x),\  a=0$, is given by:  
$f(x) = \sum\limits_{n=1}^{\infty} (-1)^{n+1}\frac{x^n}{n} = x - \frac{x^2}{2} + \frac{x^3}{3} - \frac{x^4}{4} + ...$.

**Using Ratio Test** to determine the convergence of the series,  

$\frac{a_{n+1}}{a_n} = \frac{(-1)^{n+1+1} x^{n+1}}{n+1}\times\frac{n}{(-1)^{n+1}x^n} = \frac{(-1)^{n+1}\times(-1)\times x \times x^n \times n}{(n+1)(-1)^{n+1}x^n} = \frac{-xn}{n+1}$

$L = \lim\limits_{n\to\infty}|\frac{-xn}{n+1}| = |x|$

This series converges iff $L<1$ or $|x|<1$, so then the valid range is (-1, 1).
<br>

<center><h3><b>Solution 4</b></h3></center>
$f(x) = x^\frac{1}{2}$

Find first four derivatives.

$f(x) = x^{1/2} = \sqrt{x},\  => f(a) = c^{1/2} = \sqrt{a}$

$f'(x) = \frac{1}{2}x^{-1/2},\ => f'(a) = \frac{1}{2}a^{-1/2}$

$f''(x) = -\frac{1}{4}x^{-3/2},\ => f''(a) = -\frac{1}{4}a^{-3/2}$

$f'''(x) = \frac{3}{8}x^{-5/2},\ => f'''(a) = \frac{3}{8}a^{-5/2}$

$f'^v(c) = -\frac{15}{16}x^{-7/2},\ => f'^v(a) = -\frac{15}{16}a^{-7/2}$

Following the definition of the Taylor Series, 

$f(x) = \sum\limits_{n=0}^{\infty} f^n(a)\frac{(x-a)^n}{n!}$

$$
\begin{split}
f(a) &= \frac{a^{1/2}}{0!}(x-a)^0 + \frac{a^{-1/2}}{2*1!}(x-a)^1 - \frac{a^{-3/2}}{4 * 2!}(x-a)^2 + \frac{3a^{-5/2}}{8 * 3!}(x-a)^3 + \frac{15a^{-7/2}}{16 * 4!}(x-a)^4 + ... \\
&= a^{1/2}  + \frac{a^{-1/2}}{2}(x-a) - \frac{a^{-3/2}}{8}(x-a)^2 + \frac{a^{-5/2}}{16}(x-a)^3 + \frac{a^{-7/2}}{128}(x-a)^4 + ... \\
&= \sum\limits_{n=0}^{\infty} \frac{a^{1/2 - n}}{2^{n}}(x-a)^n\\
f(a) &= \sum\limits_{n=0}^{\infty} \binom{1/2}{n}(x-a)^n\\
\end{split}
$$


Therefore, the Taylor series of $\sqrt{x}$ is $$f(a) = \sum\limits_{n=0}^{\infty} \binom{1/2}{n}(x-a)^n$$
